package be.mapariensis.kanjiryoku.net.commands;

public enum ClientCommandList {
	SAY,STATISTICS,WELCOME,FROM,INVITE,RESPOND,PROBLEM,ANSWER,PROBLEMSKIPPED,STROKE,CLEARSTROKES,RESETUI,CONFIRMADMIN
}
