package be.mapariensis.kanjiryoku.net.commands;

public enum ServerCommandList {
	BYE, REGISTER, MESSAGE, SESSIONMESSAGE, RESPOND, STARTSESSION, INVITE, KICK, LEAVE, WHOAMI, SUBMIT, SKIPPROBLEM, CLEAR, KILLSESSION, STARTGAME, LISTGAMES, ADMIN, HELLO
}
